name: mi_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: 5.7.0
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.0.0
  kiwi: ^5.0.1
  sprintf: ^7.0.0
  intl: 0.19.0
  flutter_svg: ^2.0.17
  logger: ^2.5.0
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  built_value: ^8.9.3
  built_collection: ^5.1.1
  get_localization: 3.0.0
  flutter_styled_toast: ^2.2.1
  pinput: ^5.0.1
  persistent_bottom_nav_bar: ^6.2.1
  bottom_navbar_with_indicator: ^0.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  kiwi_generator: ^4.2.1
  built_value_generator: ^8.9.3
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  fake_async: 1.3.2

dependency_overrides:
  analyzer: 6.11.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgImages/

  fonts:
    - family: FunnelDisplay
      fonts:
        - asset: assets/fonts/FunnelDisplay-Bold.ttf
        - asset: assets/fonts/FunnelDisplay-ExtraBold.ttf
        - asset: assets/fonts/FunnelDisplay-Light.ttf
        - asset: assets/fonts/FunnelDisplay-Medium.ttf
        - asset: assets/fonts/FunnelDisplay-Regular.ttf
        - asset: assets/fonts/FunnelDisplay-Semibold.ttf

